#!groovy

// Generated by IBM TransformationAdvisor
// Mon Feb 18 18:33:10 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}